/**
 * @file The export family: what an export is, what it may carry, and how large
 * it may get.
 *
 * **One file owns the family, which is the point of the rename.** The queue,
 * the job name, the two enums and the URL TTL used to live in
 * `analytics.config.ts` while the MIME, size and filter constants lived here —
 * so a reader looking for "how exports work" found half of it under analytics,
 * beside the rollup arithmetic it has nothing to do with (known-gaps #9).
 */

import type { MimeType } from './mime.config';
import { TICKET_PRIORITIES, TicketStatus } from './ticket.config';
import { AuditAction, AuditResourceType } from '../contracts/audit.contract';

/**
 * The export queue and its job name, declared once.
 *
 * Strings, and a typo does not error — it produces a queue nobody consumes and
 * an export that stays PENDING forever with a healthy-looking row. The same
 * reasoning `INGESTION_QUEUE` records.
 */
export const EXPORT_QUEUE = 'export';
export const EXPORT_JOB_NAME = 'generate-export';

/**
 * What an export is OVER.
 *
 * **Four kinds, and only two of them are analytics.** `TICKET` and `AUDIT_LOG`
 * read `tickets` and `audit_logs` directly; the two `_DAILY` kinds read
 * rollups. What all four share is the LIFECYCLE — one status machine, one
 * queue, one processor, one poll route, one table — which is why they are one
 * family rather than four features.
 *
 * This was `AnalyticsExportKind`, and the family was named for one of its four
 * kinds (known-gaps #9). The TABLE is still `analytics_exports`: renaming it is
 * a real migration under ADR 0044, where a `RENAME TABLE` in one release breaks
 * the previous image mid-rollout, and it buys a client nothing. That asymmetry
 * is deliberate — `@@map` on the model is where it is recorded.
 */
export enum ExportKind {
  /** Daily ticket rollups: the numbers behind `overview`, `volume`, `deflection`. */
  TICKET_DAILY = 'TICKET_DAILY',
  /** Daily per-agent rollups. */
  AGENT_DAILY = 'AGENT_DAILY',
  /**
   * One row per TICKET, not per day.
   *
   * The distinction that makes {@link MAX_EXPORT_ROWS} necessary: the two
   * rollup kinds are bounded by the number of days in the range, this one by a
   * tenant's whole history.
   */
  TICKET = 'TICKET',
  /** One row per audit-log entry. Bounded the same way as `TICKET`. */
  AUDIT_LOG = 'AUDIT_LOG',
}

/** The kinds that read LIVE tables rather than rollups. */
// They have no `rollupComputedAt` to disclaim and no recomputation to warn
// about, and they are the two the row cap exists for.
export const ROW_EXPORT_KINDS = [
  ExportKind.TICKET,
  ExportKind.AUDIT_LOG,
] as const satisfies readonly ExportKind[];

export const EXPORT_KINDS = Object.values(ExportKind);

/** Where an export is in its life. */
export enum ExportStatus {
  PENDING = 'PENDING',
  READY = 'READY',
  /**
   * The render or the upload failed, or the range holds more rows than one file
   * may contain. `error_log` says which.
   *
   * **An empty RESULT is not this.** That rule used to live here — "never an
   * empty file" — and its premise was a ZERO-BYTE file, where "no data" and "no
   * run" cannot be told apart. The provenance header resolves exactly that
   * ambiguity by another route: a quiet quarter is `READY`, with `# export_id`,
   * `# generated_at`, `# rollup_computed_at` and a column header above no rows.
   * That is a real answer, not an error.
   *
   * Stated here rather than only in the processor because this enum is what a
   * fifth export kind reads.
   */
  FAILED = 'FAILED',
}

/**
 * How long a download URL lives.
 *
 * **A signed URL to a file containing a tenant's full ticket history is a
 * credential.** Fifteen minutes is long enough to click a link in the response
 * and short enough that a URL pasted into a chat log expires before anybody
 * finds it.
 */
export const EXPORT_URL_TTL_SECONDS = 15 * 60;

/**
 * The content types an analytics EXPORT may carry.
 *
 * Generated by this system, never uploaded — the allowlist exists so storage's
 * confirm step can still check that what landed is what was announced.
 *
 * Shared because two services name it: ticket-service presigns the upload with
 * one of these, and `PURPOSE_POLICY[EXPORT]` decides whether to accept it.
 */
export const EXPORT_MIME_TYPES = [
  'text/csv',
  'application/json',
] as const satisfies readonly MimeType[];
export type ExportMimeType = (typeof EXPORT_MIME_TYPES)[number];

/**
 * The largest an export object may be.
 *
 * **A bug bound, not a product limit** — still, and now because something else
 * does the limiting: {@link MAX_EXPORT_ROWS} refuses an oversized row export
 * before it renders, so a tenant meets a message naming their row count rather
 * than this constant. A quarter of one tenant's rollup rows is kilobytes; this
 * exists so a runaway query cannot write a gigabyte into the bucket. It is deliberately the same figure as {@link MAX_DOCUMENT_BYTES} and
 * for an unrelated reason — do not fold them together.
 */
export const MAX_EXPORT_BYTES = 25 * 1024 * 1024;

/**
 * The longest range one export may cover.
 *
 * The **cheap** guard: a 400 at the gateway before any work happens. 92 days is
 * a quarter, which is what an export is usually for; "last year" is four calls.
 *
 * It bounds DAYS, and the byte bound counts ROWS — so this alone guarantees
 * nothing. At 300 tickets/day a 92-day export is ~28,000 rows and comfortable;
 * at 1,000/day it is ~92,000 rows and over. {@link MAX_EXPORT_ROWS} is what
 * actually holds the line; this exists so the common mistake is refused
 * instantly rather than after a count.
 */
export const MAX_EXPORT_SPAN_DAYS = 92;

/**
 * The most rows one export may contain.
 *
 * The **real** guard, checked pre-flight by the renderer against its own
 * `where` — so the refusal can say *"this range has 140,000 tickets; narrow
 * it"* rather than "your export failed".
 *
 * Sized under {@link MAX_EXPORT_BYTES}: a ticket row is roughly 200–300 bytes
 * of CSV, so 100,000 rows is 20–30 MB and the byte bound is the backstop rather
 * than the thing a tenant meets. That keeps `MAX_EXPORT_BYTES` what its
 * docblock says it is — a bug bound — because the row cap is what limits the
 * product.
 *
 * Applies to {@link ROW_EXPORT_KINDS} only. A rollup export is one row per day
 * per dimension and cannot approach it.
 */
export const MAX_EXPORT_ROWS = 100_000;

/**
 * The legal VALUES for each filter key, where the key names an enum.
 *
 * Keys are refused when unknown; values must be too, one level down. A
 * `{ status: "NONSENSE" }` that passes validation reaches Prisma, matches
 * nothing, and produces a READY zero-row export — which is the same failure
 * refusing an unknown KEY exists to prevent: a filter the caller believes
 * applied and that silently did not.
 *
 * **Exact spelling, deliberately.** These are the enum's own values, so
 * `{ status: "open" }` is refused rather than coerced — a case-insensitive
 * match would reintroduce the silent no-match for every other near-miss.
 *
 * A key absent here takes any string: `assigneeId` and `userId` are ids, not
 * enums, and a wrong one is a legitimately empty result rather than a typo the
 * system can catch.
 */
export const EXPORT_FILTER_VALUES: Partial<Record<string, readonly string[]>> =
  {
    status: Object.values(TicketStatus),
    priority: TICKET_PRIORITIES,
    action: Object.values(AuditAction),
    resourceType: Object.values(AuditResourceType),
  };

/**
 * The filter keys each export kind accepts, declared ONCE for both edges.
 *
 * Drives the gateway DTO's `@IsIn`-equivalent shape and the service's refusal
 * of an unknown key — the same "declared once" rule the sortable-field arrays
 * follow, and for the same reason: two lists that must agree eventually do not.
 *
 * The rollup kinds take none. Their whole predicate is the range and the
 * department, both of which are typed columns rather than JSON.
 */
export const EXPORT_FILTER_KEYS = {
  TICKET_DAILY: [],
  AGENT_DAILY: [],
  TICKET: ['status', 'priority', 'assigneeId'],
  AUDIT_LOG: ['action', 'resourceType', 'userId'],
} as const satisfies Record<ExportKind, readonly string[]>;
