/** @file What an analytics export may be, and how large it may get. */

import type { MimeType } from './mime.config';

/**
 * The content types an analytics EXPORT may carry.
 *
 * Generated by this system, never uploaded — the allowlist exists so storage's
 * confirm step can still check that what landed is what was announced.
 *
 * Shared because two services name it: ticket-service presigns the upload with
 * one of these, and `PURPOSE_POLICY[EXPORT]` decides whether to accept it.
 */
export const EXPORT_MIME_TYPES = [
  'text/csv',
  'application/json',
] as const satisfies readonly MimeType[];
export type ExportMimeType = (typeof EXPORT_MIME_TYPES)[number];

/**
 * The largest an export object may be.
 *
 * **A bug bound, not a product limit.** A quarter of one tenant's rollup rows is
 * kilobytes; this exists so a runaway query cannot write a gigabyte into the
 * bucket. It is deliberately the same figure as {@link MAX_DOCUMENT_BYTES} and
 * for an unrelated reason — do not fold them together.
 */
export const MAX_EXPORT_BYTES = 25 * 1024 * 1024;
