/**
 * The MIME vocabulary — every content type this system may see, declared once.
 *
 * **A spelling table, not a policy.** Nothing is permitted by appearing here;
 * the allowlists that decide what may be uploaded, stored or sent to a model
 * each name their own subset. What this buys is that those subsets are *typed*,
 * so a mistyped member is a compile error rather than a rule that silently
 * matches nothing — `'image/jpg'`, missing the `e`, used to compile cleanly and
 * refuse every JPEG upload.
 *
 * **It deliberately does NOT enforce the RELATIONSHIPS** between lists —
 * whether the gateway's allowlist is a subset of storage's, or whether every
 * storable type can reach a model. Those live in `mime.spec.ts`, where they can
 * be asserted.
 *
 * **Members are added when a list needs them, never in advance.**
 */
export const MIME_TYPES = [
  'image/png',
  'image/jpeg',
  'image/webp',
  /**
   * `.heic`/`.heif` — the iPhone camera default since iOS 11.
   *
   * Two members rather than one because the container and the codec have
   * separate types and phones emit both; accepting only `heic` rejects a
   * fraction of real uploads for a reason no user could guess.
   */
  'image/heic',
  'image/heif',
  'application/pdf',
  /** `.doc` — Word 97-2003. `document-parser.service.ts` reads it via mammoth. */
  'application/msword',
  /** `.docx` — the OOXML successor. Same parser. */
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  /**
   * `.xlsx` — attachable, and read by nobody yet.
   *
   * No parser reads it: `document-parser.service.ts` handles `.doc`/`.docx` and
   * stops there. It is here so a customer can send a spreadsheet to an agent,
   * which is a human-to-human path — see `ALLOWED_ATTACHMENT_MIME_TYPES`.
   */
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  /** Analytics exports only — generated by this system, never uploaded. */
  'application/json',
  'text/plain',
  'text/markdown',
  'text/csv',
] as const;

export type MimeType = (typeof MIME_TYPES)[number];

/**
 * MIME type -> the file extension an object of that type is stored under.
 *
 * Partial: a type with no meaningful extension has no entry and resolves to
 * {@link UNKNOWN_EXTENSION} via {@link extensionFor}.
 *
 * Declared `as const satisfies` so the values stay literal types — types derived
 * from this table (such as `DocumentFileType`) collapse to `string` under a
 * plain annotation.
 *
 * Never derive an extension from a user-supplied filename; `invoice.pdf.php`
 * would become a `.php` object.
 */
export const EXTENSION_BY_MIME = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/webp': 'webp',
  'image/heic': 'heic',
  'image/heif': 'heif',
  'application/pdf': 'pdf',
  'application/msword': 'doc',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
    'docx',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'xlsx',
  'text/plain': 'txt',
  'text/markdown': 'md',
  // Needed because `.csv` became ATTACHABLE, not because it is exported.
  // `EXPORT_MIME_TYPES` has used this type since exports existed, and exports
  // are generated and named by this system rather than uploaded — so the
  // "every uploadable type has an extension" rule never reached it before.
  'text/csv': 'csv',
} as const satisfies Partial<Record<MimeType, string>>;

/** What a type with no extension mapping is filed as. */
export const UNKNOWN_EXTENSION = 'bin';

export function extensionFor(contentType: string): string {
  return (
    (EXTENSION_BY_MIME as Record<string, string>)[contentType] ??
    UNKNOWN_EXTENSION
  );
}
