// ASK This `docblock` seems to be invalid
/**
 * The MIME vocabulary — every content type this system may see, declared once.
 *
 * **This is a spelling table, not a policy.** Nothing is permitted by appearing
 * here; the allowlists that decide what may be uploaded, stored or sent to a
 * model each name their own subset. What this buys is that those subsets are
 * *typed*, so a mistyped member is a compile error rather than a rule that
 * silently matches nothing.
 *
 * **The hazard is specific and was live.** `PurposePolicy.mimeAllowlist` was
 * `readonly string[]`, so `'image/jpg'` — the natural misspelling, missing the
 * `e` — compiled cleanly and refused every JPEG upload with a message naming a
 * type the user had not sent. Typed as `readonly MimeType[]`, it does not
 * build. That was the standing FIXME on `PurposePolicy`.
 *
 * **`'image/png'` had been written out eleven times across five files** — two
 * configs in `libs/common`, two in storage-service, and a private `const` in a
 * DTO — with no relationship between them that anything checked.
 *
 * **What this deliberately does NOT do is enforce the RELATIONSHIPS.** A shared
 * vocabulary makes every list spell types the same way; it says nothing about
 * whether the gateway's allowlist is a subset of storage's, or whether every
 * storable type can reach a model. Those are invariants between lists, and they
 * live in `mime.spec.ts` where they can be asserted rather than hoped for.
 *
 * **Members are added when a list needs them, never in advance.** A vocabulary
 * entry no allowlist names is a type nobody can send, sitting in the file that
 * exists to say what may be sent — which is the shape of the problem this
 * replaces.
 */
export const MIME_TYPES = [
  'image/png',
  'image/jpeg',
  /**
   * Only in `AI_ELIGIBLE_MIME_TYPES`, deliberately — see that constant. No
   * storage policy accepts it today, and the invariant that matters runs the
   * other way.
   */
  'image/gif',
  'image/webp',
  'application/pdf',
  /** Analytics exports only — generated by this system, never uploaded. */
  'application/json',
  'text/plain',
  'text/markdown',
  'text/csv',
] as const;

export type MimeType = (typeof MIME_TYPES)[number];

/**
 * MIME type -> the file extension an object of that type is stored under.
 *
 * Partial: a type with no meaningful extension has no entry and resolves to
 * {@link UNKNOWN_EXTENSION} via {@link extensionFor}.
 *
 * Declared `as const satisfies` so the values stay literal types — types derived
 * from this table (such as `DocumentFileType`) collapse to `string` under a
 * plain annotation.
 *
 * Never derive an extension from a user-supplied filename; `invoice.pdf.php`
 * would become a `.php` object.
 */
export const EXTENSION_BY_MIME = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/webp': 'webp',
  'application/pdf': 'pdf',
  'text/plain': 'txt',
  'text/markdown': 'md',
} as const satisfies Partial<Record<MimeType, string>>;

/** What a type with no extension mapping is filed as. */
export const UNKNOWN_EXTENSION = 'bin';

export function extensionFor(contentType: string): string {
  return (
    (EXTENSION_BY_MIME as Record<string, string>)[contentType] ??
    UNKNOWN_EXTENSION
  );
}
