-- `ticket_assignments.assigned_by_id` was nullable for a case that cannot occur.
-- `writeAssignment` is its only writer and takes `requireActor(context)`, and
-- `load` refuses a caller with no identity, so the null never had a producer.
-- known-gaps #12.
--
-- ADR 0044 (expand and contract, never in one release): this is the CONTRACT
-- step, and the expand step already happened -- every image that has ever run
-- writes a value into this column. There is no rollout window in which an older
-- image would insert a null, so one release is correct here.
--
-- Verified before writing: `SELECT count(*) FROM ticket_assignments WHERE
-- assigned_by_id IS NULL` is 0 on every database this reaches, and the statement
-- below was executed against a scratch copy of the table -- both with the table
-- empty (it succeeds) and with one null row present (it refuses, which is what
-- would hold the init container at `Init:Error`). Development runs `prisma db
-- push`, so nothing else executes this file before a deploy does.
--
-- **The directory name must sort AFTER `0_init`.** `schema-contract.spec.ts`
-- check 3 reads `migrations[0]` from a sorted list and requires it to be over
-- 500 bytes -- the init migration, not this one-statement file. `20260906_...`
-- sorts second because '0' < '2'; a rename that put a small file first would
-- turn that check red for a reason that has nothing to do with what it guards.
ALTER TABLE "ticket_assignments" ALTER COLUMN "assigned_by_id" SET NOT NULL;
