/**
 * @file The one way `.env` files are read in tests — parser and key census.
 *
 * Lifted from the gateway's `env.validation.spec.ts`, which parsed the REAL
 * `.env.test` to validate it against the real Joi schema, and promoted to the
 * single counting rule for every env scan. The promotion is the point, not
 * the reuse: doc 70's own drift table was generated by an ad-hoc `grep -cE`
 * and was one edit-generation stale by the time it was implemented — two ways
 * of counting the same file is how a guard and a document disagree about
 * whether they agree.
 */

/**
 * Active `KEY = value` lines, as the entries dotenv would load.
 *
 * Comments and blanks skipped; the first `=` splits, both halves trimmed —
 * the same tolerance dotenv itself has for the `KEY = value` spacing these
 * files use.
 */
export function parseEnvFile(content: string): Record<string, string> {
  return Object.fromEntries(
    content
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#') && line.includes('='))
      .map((line) => {
        const at = line.indexOf('=');

        return [line.slice(0, at).trim(), line.slice(at + 1).trim()];
      }),
  );
}

/**
 * Every variable the file DOCUMENTS — active lines plus commented-out ones.
 *
 * `# REDIS_DB = 0` is how an optional variable becomes discoverable without
 * being set, so a census that read only active lines would report every such
 * documentation as absence. The commented form must still LOOK like an
 * assignment (`# KEY =`), so prose that merely mentions a variable's name
 * does not count as documenting it.
 */
export function envDocumentedKeys(content: string): Set<string> {
  const keys = new Set<string>();

  for (const raw of content.split('\n')) {
    const line = raw.trim();
    const match = /^#?\s*([A-Z][A-Z0-9_]*)\s*=/.exec(line);

    if (match) keys.add(match[1]);
  }

  return keys;
}
