import { StoragePurpose, type MimeType } from '@synapsedesk/common';

/**
 * What each purpose allows — §2.1.
 *
 * ONE table, not a `switch` scattered across handlers. Three things have to
 * move together whenever a purpose changes (the allowlist, the cap, and the
 * path prefix), and three `switch` statements in three files is how two of them
 * end up updated.
 *
 * `Record<StoragePurpose, …>` rather than a partial map: adding a purpose to
 * the enum without a policy is then a compile error, which is the only moment
 * anyone is thinking about it.
 */
export type PurposePolicy = {
  mimeAllowlist: readonly MimeType[];
  maxSizeBytes: number;
  /** The path segment under `organizations/{orgId}/`. */
  prefix: string;
  /**
   * Whether the path CAN take a second owner id — a message, for an attachment.
   *
   * **Permitted, not required** It was required until the
   * one-shot case turned up: presign and confirm both took a `message_id`, so
   * the attachment row could only exist after the message did, while
   * `invoke_ai` runs during the create. The screenshot arrived a moment too
   * late to be read.
   *
   * Now a ticket attachment may be presigned before its message exists, and the
   * segment is simply absent from the path. **Nothing depends on the shape**:
   * no code in this repo parses an object path, there is no prefix-based
   * delete, and the authorization is the Redis record plus the tenant check —
   * never the path. What the segment buys is a readable bucket, which is worth
   * having when there is a message to name and worth nothing when there is not.
   */
  allowsSecondaryOwner: boolean;
};

export const PURPOSE_POLICY: Record<StoragePurpose, PurposePolicy> = {
  [StoragePurpose.AVATAR]: {
    // Images only, and no SVG — an SVG is a document that can carry script, so
    // it is the one image type that behaves like an executable when served.
    mimeAllowlist: ['image/png', 'image/jpeg', 'image/webp'],
    maxSizeBytes: 2 * 1024 * 1024,
    prefix: 'avatars',
    allowsSecondaryOwner: false,
  },
  [StoragePurpose.TICKET_ATTACHMENT]: {
    mimeAllowlist: [
      'image/png',
      'image/jpeg',
      'image/webp',
      'application/pdf',
      'text/plain',
    ],
    maxSizeBytes: 10 * 1024 * 1024,
    prefix: 'tickets',
    allowsSecondaryOwner: true,
  },
  [StoragePurpose.EXPORT]: {
    // Generated BY US, not uploaded: the allowlist exists so the confirm step
    // can still check that what landed is what was announced, and a narrow one
    // costs nothing when there is exactly one producer.
    mimeAllowlist: ['text/csv', 'application/json'],
    // A quarter of one tenant's rollup rows is kilobytes; the cap is here to
    // bound a bug, not a legitimate file.
    maxSizeBytes: 25 * 1024 * 1024,
    prefix: 'exports',
    allowsSecondaryOwner: false,
  },
  [StoragePurpose.DOCUMENT]: {
    // Domain C's knowledge base. `ingestion-service` is the caller, and
    // `ALLOWED_DOCUMENT_MIME_TYPES` in libs/common mirrors this list — widen
    // BOTH together when the real parser handles more formats, or the gateway
    // starts accepting a type this refuses.
    mimeAllowlist: ['application/pdf', 'text/plain', 'text/markdown'],
    maxSizeBytes: 25 * 1024 * 1024,
    prefix: 'documents',
    allowsSecondaryOwner: false,
  },
};

/**
 * Re-exported so call sites here need one import, not two.
 *
 * The table itself lives in `libs/common` beside the vocabulary: storage-service
 * names an object's extension and ingestion-service writes the same string into
 * `documents.file_type`, and they had drifted into two tables mapping the same
 * thing.
 */
export { extensionFor } from '@synapsedesk/common';
