syntax = "proto3";

package auth;

import "google/protobuf/timestamp.proto";

// Request/Response definitions for authentication

message RegisterRequest {
  string email = 1;
  string password = 2;
  string full_name = 3;
}

message RegisterResponse {
  string user_id = 1;
  string organization_id = 2;
  string email = 3;
  bool requires_email_verification = 4;
}

message LoginRequest {
  string email = 1;
  string password = 2;
  string device_name = 3;
}

message LoginResponse {
  string access_token = 1;
  string refresh_token = 2;
  UserResponse user = 3;
  bool requires_two_factor = 4;
}

message TwoFactorLoginResponse {
  string two_factor_token = 1;
  bool requires_two_factor = 2;
}

// In Proto3, the first enum value must be 0 and serves as the default.
enum Gender {
  UNSPECIFIED = 0;
  MALE = 1;
  FEMALE = 2;
  OTHER = 3;
}

// Only use 'optional' on primitive scalar fields because google.protobuf fields are always optional by default
message UserResponse {
  string id = 1;
  string organization_id = 2;
  string full_name = 3;
  optional string avatar_url = 4;
  string email = 5;
  bool is_email_verified = 6;
  optional string phone_number = 7;
  bool is_phone_verified = 8;
  optional google.protobuf.Timestamp dob = 9;
  Gender gender = 10;
  optional google.protobuf.Timestamp last_login_at = 11;
  bool is_locked = 12;
  bool is_two_factor_enabled = 13;
  google.protobuf.Timestamp created_at = 14;
  google.protobuf.Timestamp updated_at = 15;
}

service AuthService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
}